dist: trusty
sudo: required

language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - openjdk8

before_install: 
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

before_script:
  - echo "" > $HOME/.gradle/gradle.properties
  - echo "org.gradle.configureondemand=true" >> $HOME/.gradle/gradle.properties
  - echo "org.gradle.jvmargs=-Xmx1536M" >> $HOME/.gradle/gradle.properties
  - echo "org.gradle.caching=true" >> $HOME/.gradle/gradle.properties
  - echo "org.gradle.parallel=true" >> $HOME/.gradle/gradle.properties


script:
  - ./gradlew build -s

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android
