---
project_identifier: open-link-with

files:
  -
    source: '/app/src/main/res/values/strings.xml'
    translation: '/app/src/main/res/values-%android_code%/strings.xml'
    languages_mapping:
      android_code:
        ar: ar
        de: de
        es-ES: es
        fi: fi
        fr: fr
        id: in
        it: it
        ja: ja
        ko: ko
        pl: pl
        pt-BR: pt-rBR
        pt-PT: pt-rPT
        ru: ru
        sv-SE: sv
        tr: tr
        uk: uk
        vi: vi
        zh-CN: zh-rCN

